### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by prtomasi** [dmitriykuptsov/tacacsgui#2]
After complete the setup and create users + group, tacacsgui updated /usr/local/etc/tac_plus.cfg according to front-end parameters

I created a temp password and updated via http://N.N.N.N:8080/auth/reset_tacacs_password/
tacacsgui accepted the old password and created the new one

But I can't login in a switch, tac_plus is rejecting both users I created.

2022-01-04 23:05:24 +0000       172.X.Y.Z    tomasi  mgmt            pap login failed (denied)

Is there any additional config needed in tacacsgui to allow mavis and pap login?

#

EDIT 05/01/2020 11:00

After change 'login' parameter to 'password' parameter in user section of /usr/local/etc/tac_plus.cfg file (and synchronizer.sh disabled in crontab), both users were able to login:

user = paulo {
        **password** = crypt $1$RegT0RSC$FO/Rj3VKe9pnU1122FA0r1
        member = READ
        }

user = tomasi {
        **password** = crypt $1$Z/vw9ZLA$oYNTdAVHAvJC2dnKgjzux1
        member = ADMIN
        }

Unfortunatelly I don't have knowledge about python to change this config in front-end
Is it possible to update the code?

**Comment by dmitriykuptsov** [comment]
Can you show me the configuration file contents that GUI creates, without your modifications?

**Comment by dmitriykuptsov** [comment]
I mean can you post here the configuration file that GUI creates when you press Build and deploy button? I suspect that you are forgetting to add something in GUI part. Cheers

**Comment by dmitriykuptsov** [comment]
Here is the simple configuration take from https://www.pro-bono-publico.de/projects/tac_plus.html

#!/usr/local/sbin/tac_plus
id = spawnd {
    listen = { port = 49 }
    listen = { port = 4949 }
    # see the spawnd configuration guide for further configuration options
}

id = tac_plus {
    accounting log = /var/log/tac_plus/%Y/%m/%d.log
    retire limit = 1000
    mavis module = external {
        exec = /usr/local/lib/mavis_tacplus_passwd.pl
        # see the MAVIS configuration manual for more options and other modules
    }
    login backend = mavis

    host = world {
        welcome banner = "\nHitherto shalt thou come, but no further. (Job 38.11)\n\n"
        key = QaWsEdRfTgY
        enable 15 = clear test
        address = 0.0.0.0/0
    }

    group = readwrite {
        default service = permit
        service = shell {
            default command = permit
            set priv-lvl = 15
        }
    }

    group = getconfig {
        default service = permit
        service = shell {
            set autocmd = "sho run"
            set priv-lvl = 15
        }
    }

    user = marc {
       login = crypt $1$xxxxxxxx$hDZPHghXe8XvoHeFdqUwm/
       member = readwrite@world
       member = getconfig@192.168.0.0/16
    }
}

As us can see in the user section it is login, not password. Are you sure that you are using the correct sources for the TACACS+ daemon? The GUI creates configuration according to the implementation specified in https://www.pro-bono-publico.de/projects/tac_plus.html. Please double check that you are using the correct binaries for the TACACS+, since my implementation should work correctly and in fact it was tested against the above mentioned binaries.

**Comment by dmitriykuptsov** [comment]
See section 3.4. Sample Configuration for the reference @ https://www.pro-bono-publico.de/projects/tac_plus.html

**Comment by prtomasi** [comment]
Hi, Dmitriy, thanks for your answer

Maybe Marc Huber didn't update the sample config in the site

I followed the sample config located in DEVEL.202109260929.tar.bz2\PROJECTS\tac_plus\sample\tac_plus.cfg

```

#!../../../sbin/tac_plus

id = spawnd {
	listen = { port = 4949 }
	spawn = {
		instances min = 1
		instances max = 10
	}
	background = no
}

id = tac_plus {
	debug = PACKET AUTHEN AUTHOR

	access log = /tmp/access.log
	authorization log = /tmp/author.log
	accounting log = /tmp/acct.log

	host = world {
		address = ::/0
		prompt = "Welcome\n"
		enable 15 = clear secret
		key = cisco
	}

	group = admin {
		default service = permit
		service = shell {
			default command = permit
			default attribute = permit
			set priv-lvl = 15
		}
	}

	group = guest {
		default service = permit
		enable = deny
		service = shell {
			default command = permit
			default attribute = permit
			set priv-lvl = 1
		}
	}

	user = cisco {
		password = clear cisco
		member = admin
		service = shell {
			default command = permit
			default attribute = permit
			set priv-lvl = 15
		}
	}

	user = readonly {
		password = clear readonly
		member = guest
	}
}

```

In the last version he uses `password` instead of `login`

and luckly `password` worked to my cisco-like device

**Comment by dmitriykuptsov** [comment]
Hi, Ok. I see. I have pushed a change. Can you please pull and test the system now?

**Comment by dmitriykuptsov** [comment]
I have tested the change. Seems to work now. 

dmitriy@hipresponder:~/.local/bin$ ./tacacs_client -k debwivPomBewkAtNifHachvarsindAv8 -H localhost -v -u dmitriy authenticate
password for dmitriy: 
status: PASS
dmitriy@hipresponder:~/.local/bin$ ./tacacs_client -k debwivPomBewkAtNifHachvarsindAv8 -H localhost -u dmitriy -v authorize -c service=shell cmd=show cmdarg=version
status: PASS
dmitriy@hipresponder:~/.local/bin$

**Comment by prtomasi** [comment]
It worked, thanks

#

```
tomasi@tacacs-01:/# ./usr/local/bin/tacacs_client -k 7u72oo2Agj1950XHJP90H1x2G -H localhost -v -u paulo authenticate
password for paulo:
status: PASS
```

#

Read user not allowed to enter config mode:

```
login as: paulo
Keyboard-interactive authentication prompts from server:
| Password:
End of keyboard-interactive prompts from server
Welcome to the DmOS CLI
paulo connected from 10.1.1.10 using ssh on SW2-ACE-NNN-NNN-01
SW2-ACE-NNN-NNN-01# conf
Aborted: permission denied
SW2-ACE-NNN-NNN-01#
```
