### ISSUE TITLE
Problem with syslog messages

### ISSUE THREAD

**Issue by nadmin1706** [dmitriykuptsov/tacacsgui#5]
The software is running but my syslog filled up with these Log:

python3[12732]: Job "auto_deploy (trigger: interval[0:01:00], next run at: 2023-05-15 14:02:24 CEST)" raised an exception
May 15 14:01:24 revox-b77 python3[12732]: Traceback (most recent call last):
May 15 14:01:24 revox-b77 python3[12732]:   File "/usr/local/lib/python3.9/dist-packages/apscheduler/executors/base.py", line 125, in run_job
May 15 14:01:24 revox-b77 python3[12732]:     retval = job.func(*job.args, **job.kwargs)
May 15 14:01:24 revox-b77 python3[12732]:   File "/opt/tacacsgui/app/__init__.py", line 63, in auto_deploy
May 15 14:01:24 revox-b77 python3[12732]:     configurations = Configuration.query.all();
May 15 14:01:24 revox-b77 python3[12732]:   File "/usr/local/lib/python3.9/dist-packages/flask_sqlalchemy/model.py", line 31, in __get__
May 15 14:01:24 revox-b77 python3[12732]:     cls, session=cls.__fsa__.session()  # type: ignore[arg-type]
May 15 14:01:24 revox-b77 python3[12732]:   File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/scoping.py", line 218, in __call__
May 15 14:01:24 revox-b77 python3[12732]:     sess = self.registry()
May 15 14:01:24 revox-b77 python3[12732]:   File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/util/_collections.py", line 640, in __call__
May 15 14:01:24 revox-b77 python3[12732]:     key = self.scopefunc()
May 15 14:01:24 revox-b77 python3[12732]:   File "/usr/local/lib/python3.9/dist-packages/flask_sqlalchemy/session.py", line 102, in _app_ctx_id
May 15 14:01:24 revox-b77 python3[12732]:     return id(app_ctx._get_current_object())  # type: ignore[attr-defined]
May 15 14:01:24 revox-b77 python3[12732]:   File "/usr/local/lib/python3.9/dist-packages/werkzeug/local.py", line 508, in _get_current_object
May 15 14:01:24 revox-b77 python3[12732]:     raise RuntimeError(unbound_message) from None
May 15 14:01:24 revox-b77 python3[12732]: RuntimeError: Working outside of application context.
May 15 14:01:24 revox-b77 python3[12732]: This typically means that you attempted to use functionality that needed
May 15 14:01:24 revox-b77 python3[12732]: the current application. To solve this, set up an application context
May 15 14:01:24 revox-b77 python3[12732]: with app.app_context(). See the documentation for more information.

I am not a programmer so i cant fix the code.
Is there possibillity to put the logging to /dev/null

regards

Matthias

**Comment by dmitriykuptsov** [comment]
Hi,

Try putting the following two lines in the systemd startup file (if you do not need the logs):

[Service]
StandardOutput=null
StandardError=null

If you do need the logs you can redirect them to file:

[Service]
StandardOutput=/var/logs/tacacsgui.log
StandardError=/var/logs/tacacsgui.error.log


Best regards,
Dmitriy

**Comment by dmitriykuptsov** [comment]
I will try to investigate the issue with the Exception

**Comment by nadmin1706** [comment]
Perfect thangs. 

Matthias

**Comment by dmitriykuptsov** [comment]
Did as per instructions presented here: https://www.linuxjournal.com/content/configuring-tacacs-server-simple-gui

After clean install the system works as expected and no errors in the logs.

**Comment by dmitriykuptsov** [comment]
Cannot reporduce the issue

**Comment by nadmin1706** [comment]
I installed it on a fresh debian 11 bullseye. The error ocours every minute , when autodeploy is working.
Perhaps something is special in Debian 11 Python 3.9.

regards

Matthias

**Comment by dmitriykuptsov** [comment]
Could be I have used fresh install of Ubuntu 18.04.6 LTS

**Comment by dmitriykuptsov** [comment]
It is likely that it does not sync the configuration file. Can you check the contents of tacacs configuration file:

cat /usr/local/etc/tac_plus.cfg

Auto deploy should pickup the local configuratoin (created by GUI) and copy it to /usr/local/etc/

**Comment by dmitriykuptsov** [comment]
Ok I have removed auto deploy thread. Could you please pull and test again?

**Comment by dmitriykuptsov** [comment]
Auto deploy is needed in order to pick up the changes in passwords done by users using the "Chnage password" form

**Comment by dmitriykuptsov** [comment]
Can you pull again and retest?

**Comment by nadmin1706** [comment]
That looks great. I replaced the ini.py and get no error in Log. The config-replace works two.

regards

Matthias

**Comment by dmitriykuptsov** [comment]
Do you mean you pulled my changes, replaced \_\_init\_\_.py and it worked for you?

**Comment by nadmin1706** [comment]
Yes so it isVon meinem/meiner Galaxy gesendet
-------- Ursprüngliche Nachricht --------Von: Dmitriy Kuptsov ***@***.***> Datum: 16.05.23  13:56  (GMT+01:00) An: dmitriykuptsov/tacacsgui ***@***.***> Cc: nadmin1706 ***@***.***>, State change ***@***.***> Betreff: Re: [dmitriykuptsov/tacacsgui] Problem with syslog messages (Issue #5) 
Do you mean you pull my changes, replaced init.py and it worked for you?

**Comment by dmitriykuptsov** [comment]
Thanks!
